name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: keyboards/handwired/dactyl_manuform/4x5/

      - name: Build firmware
        run: qmk compile -kb handwired/dactyl_manuform/4x5 -km default

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: keyboard_firmware
          path: |
            *.hex
            *.bin
            *.uf2
